#!/bin/sh
## Execute neuron in parallel

ARCH=`arch`
NRNHOME="$HOME/neuron/nrn/nrnmpi"
NRNBIN="${NRNHOME}/${ARCH}/bin/"
NRNIV="${NRNBIN}nrniv"
LNRNMECH="./mpi/.libs/libnrnmech.so"
#MPIBIN="$HOME/mpich2-1.0/bin/"
MPIBIN=/usr/bin/
MPIRUN="${MPIBIN}mpirun"

"${MPIRUN}" -np 3 "${NRNIV}" -dll "${LNRNMECH}" "$@"






